title: "Gray - Amazon Storefront"
email: mggicay@gmail.com
timezone: UTC
baseurl: "/storefront"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Grace
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  gray:
    name: Grace Icay
    display_name: Gray
    avatar: 'assets/images/gray.png'
    email: mggicay@gmail.com
    web: https://grayinfilm.com
    instagram: https://www.instagram.com/gray__in__film
    description: "This page is created by Gray for posting Amazon Affiliate Links"

# Social
social:
  instagram: https://www.instagram.com/gray__in__film/
  linkedin: https://www.linkedin.com/in/mary-grygjeanne-grace-icay-109184140/
  github: http://github.com/digracesion
  medium: https://medium.com/@todorokis
  behance: https://www.behance.net/mggicay

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives